logger:
  preset: "dev"        # "dev"|"prod"
  level: "debug"       # "debug"|"info"|"warn"|"error"|"dpanic"|"panic"|"fatal"
  encoding: "console"  # "console"|"json"
  outputPaths:
    - "stdout"
  errorOutputPaths:
    - "stdout"

storage:
  type: "memory"          # "memory"|"sql"
  dbname: "calendar"      # need be set in env if type = "sql"
  dbhost: "localhost"     # need be set in env if type = "sql"
  dbport: 5432            # need be set in env if type = "sql"
  dbsslmode: "disable"
  dbuser: "cuser"         # need be set in env if type = "sql"
  dbpassword: "cpassword" # need be set in env if type = "sql"
  dbtimeout: "5s"

server:
  host: "localhost"
  port: 8081
