CREATE DATABASE calendar;

CREATE USER cuser WITH ENCRYPTED PASSWORD 'cpassword';

GRANT ALL ON DATABASE calendar TO cuser;

ALTER DATABASE calendar OWNER TO cuser;

GRANT USAGE, CREATE ON SCHEMA PUBLIC TO cuser;
